# Generated by Django 3.0.8 on 2020-07-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=50)),
                ('word', models.CharField(max_length=50, null=True)),
                ('user_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villager', models.CharField(max_length=50)),
                ('wolf', models.CharField(max_length=50)),
            ],
        ),
    ]
